### ISSUE TITLE
BasicA a Name for a Very Old BASIC Dialect

### ISSUE THREAD

**Issue by olimaticer** [mougino/basica#1]
See:
http://en.community.dell.com/support-forums/desktop/f/3514/t/3831104

**Comment by mougino** [comment]
Yes I know, not an issue. A precedence search gave no other result than this variant lastly used 40 years ago... (ans which is the ancestor of GW Basic btw). See https://en.wikipedia.org/wiki/BASIC#IBM_PC_and_compatibles
